image: jupyter/datascience-notebook:83ed2c63671f

stages:
  - render

make:
  stage: render
  script:
    - jupyter nbconvert --exec --to html --output anomaly-detection.html anomaly-detection.ipynb
  artifacts:
    paths:
      - $CI_PROJECT_DIR/anomaly-detection.html

